### ISSUE TITLE
Chapter 5 upload needs fixing please

### ISSUE THREAD

**Issue by jhughes4te2** [PacktPublishing/Spring-Microservices#1]
Chapter 5 is not in the correct directory and is incomplete (top level pom references non-existent modules)

**Comment by tamami** [comment]
Chapter 5 need `book` module for `book-service`

**Comment by hieung** [comment]
Chapter 5 need **eureka-server** module

**Comment by ghost** [comment]
You can find those modules in [rajeshrv/SpringMicroservice](https://github.com/rajeshrv/SpringMicroservice).

**Comment by tamami** [comment]
so, this issue should be closed isn't?

**Comment by techsachinkumar** [comment]
Closed.
